### ISSUE TITLE
Catch HTTP Errors

### ISSUE THREAD

**Issue by bergkoet** [bergkoet/oscar#9]
This seems to happen occasionally due to failed communication with Digit-Eyes:

Waiting for scanner data
Scanned barcode '077890422069'
Traceback (most recent call last):
  File "/var/oscar/scan.py", line 235, in <module>
    desc = u.get_description(barcode)
  File "/var/oscar/scan.py", line 64, in get_description
    json_blob = urllib2.urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by bergkoet** [comment]
Handled in 01c5cb057e1d3d81038cadf91f30f2f3afc33e37
